### PR TITLE
add ParseMode config for Telegram

### PR DESCRIPTION
**Pull request by ivmaks**
add support Markdown and HTML ParseMode
https://core.telegram.org/bots/api#formatting-options

### CODE REVIEW

**Comment by BDelacour** [comment]
Hey @marcelcorso, may you have some time to review this ? It is a simple and cool feature for Telegram

**Comment by marcelcorso** [comment]
I'm sorry we let this go stale @BDelacour. Can you help us review the change?

**Comment by BDelacour** [comment]
Yes of course @marcelcorso, I'll tests this in some time

**Comment by marcelcorso** [comment]
@BDelacour thank you!

**Comment by BDelacour** [comment]
@marcelcorso I suggested some changes. Would you like me to modify the code ? (Since 3 years, I don't know if @ivmaks is still following the project)

**Comment by marcelcorso** [comment]
@BDelacour If you like to improve some thinks please do another PR. That would be great!! Thanks

**Comment by BDelacour** [comment]
Duplicate of #104

**Pull request merged**
